import type { NextPage, GetStaticProps, GetStaticPaths, GetServerSideProps } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import GetCatAPI from '../common/types'

const Home: NextPage = (props: any) => {
  const {id, url, webpurl, x, y} = props.data; 
  console.log(url);

  const myLoader = ({ src, width, quality }) => {
    return url;
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Image
      loader={myLoader}
      src="me.png"
      alt="cat"
      width={700}
      height={500}
    />
    {JSON.stringify(props)}
    </>
  )
}



export const getStaticProps: GetStaticProps = async (context) => {
  const res = await fetch('https://thatcopy.pw/catapi/rest/'); 
  const data: GetCatAPI = await res.json(); 

  return {
    props: { data },
  }
}

export default Home
