import type { NextPage, GetStaticProps, GetStaticPaths, GetServerSideProps } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import imageLoader from '../../imageLoader'
import { Character, GetCharacterResults } from '../common/types'

const Home: NextPage<{characters: Character[]}> = ({characters}) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {characters.map((character: Character) => {
        return (
          <li key={character.id}>{character.name}

          <Image 
            loader={imageLoader}
            unoptimized
            src={character.image}
            alt={character.name}
            width="200"
            height="200"
          />
          </li>
        )
      })}
    </>
  )
}

export const getStaticProps: GetStaticProps = async (context) => {
  const res = await fetch('https://rickandmortyapi.com/api/character'); 
  const {results}: GetCharacterResults = await res.json(); 

  return {
    props: { characters: results },
  }
}

export default Home
